# Generated by Django 5.2.6 on 2025-09-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='time',
            new_name='created_at',
        ),
    ]
